# Generated by Django 6.0.6 on 2026-07-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_attachment_reply_voice_note_thread_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Common abbreviation, e.g. UNN, UNILAG, FUTA', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('school_type', models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('college_of_education', 'College of Education'), ('monotechnic', 'Monotechnic')], default='university', max_length=30)),
                ('state', models.CharField(blank=True, help_text='Nigerian state where the school is located', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['short_name'], name='forum_schoo_short_n_103d5b_idx')],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='forum.school'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['school', 'code'], name='forum_depar_school__3276a1_idx'),
        ),
    ]
